# Dependabot configuration file.

version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase-if-necessary