name: dero_dvm_basic
description: DVM-BASIC parser to convert a Dero smart contract into a data structure.
version: 0.2.7

repository: https://github.com/Ez3kiel-dev/dero_dvm_basic

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  path: ^1.9.0
  petitparser: ^6.0.2

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^2.5.3
  lints: ^4.0.0
  test: ^1.25.5
