name: dero_dvm_basic
description: DVM-BASIC parser to convert a Dero smart contract into a data structure.
version: 0.2.5

repository: https://github.com/Ez3kiel-dev/dero_dvm_basic

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  path: ^1.8.3
  petitparser: ^5.3.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.1
  test: ^1.22.0