name: dero_dvm_basic
description: DVM-BASIC parser to convert a Dero smart contract into a data structure.
version: 0.2.6

repository: https://github.com/Ez3kiel-dev/dero_dvm_basic

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  path: ^1.8.3
  petitparser: ^6.0.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  lints: ^4.0.0
  test: ^1.24.9
